#ifndef AR_GL_SHADER_H
#define AR_GL_SHADER_H
#ifdef AR_USE_OPENGL

#define AR_SHADER_VERTEX   GL_VERTEX_SHADER
#define AR_SHADER_FRAGMENT GL_FRAGMENT_SHADER
#define AR_SHADER_GEOMETRY GL_GEOMETRY_SHADER

#endif
#endif
